services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=3000
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - psql-db
    environment:
      - DB_URL=${DATABASE_URL}
  psql-db:
    # pull the postgres image from DockerHub
    image: postgres:16
    container_name: psql-docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  # to persist the database tables
  pgdata: {}